### ISSUE TITLE
Icon for the extension list

### ISSUE THREAD

**Issue by kav2k** [napsternxg/ReadLater#11]
The extension currently displays a default icon for the extension list.

One key needs to be added to the manifest:

      "icons": {
        "48": "icon.png"
      },

(Not doing a PR for this, it's easier to just add on your side)

**Comment by kav2k** [comment]
By the way, would you consider reworking the icon?

Ideally, you should have an icon set (16x16, 32x32, 48x48, 128x128 with padding).
The current icon is also not very intuitive.

**Comment by napsternxg** [comment]
This is closed via #21
