### ISSUE TITLE
Shift all the core code into a common file core.js

### ISSUE THREAD

**Issue by napsternxg** [napsternxg/ReadLater#16]
Shift all the core code into a common file `core.js`, only the front end codes should be in `popup.js` and all the background codes should be in `background.js`

**Comment by kav2k** [comment]
Can't say I agree with your approach so far in `new-api`.

Your "core" does two very different things (including front-end processing) depending on `is_popup`.

I thought the idea was to separate "model" (interfacing with `chrome.storage`) and "view" (UI rendering / processing).

I don't actually think that background and popup should share code at all. A more clean approach would be to move all actual list processing to background, and do sort-of-RPC with `sendMessage` from popup to retrieve / modify data.

**Comment by napsternxg** [comment]
@kav2k I agree, this was written in haste last night. Yes the idea is the separate the model and the UI. The thing I am trying to implement is the following:

1. Each of background and popup have a way of accessing the storage and adding the URL from the current tab or from a context URL (using context menu)
2. The backend takes the urlItem which is generated by a helper function, and then adds it to the storage.
3. The backend supports the following calls: `addURL(urlItem)`, `removeURL(url)`, `clearAll()`. Each call modifies the storage. 
4. All UI updates happen as a callback of each operation, e.g. updating the list shown. 
5. UI updates for changing the counters, and messages should also be triggered whenever the storage is changed. This can be done by adding a Listener to the `storage.onChanged` event. 

NOTE: Although I don't expect the background and popup to ever run into any concurrency issues, I don't want to maintain any global state of the application which is required to be updated, except for the UI elements locked to that script. So the count will extracted based on each change in storage. 

What do you think about this design.

**Comment by napsternxg** [comment]
@kav2k I have made changes to the API and tested it on my side. It seems to be working. Would you like to have a look. The branch is new-api.

**Comment by kav2k** [comment]
1. Without `chrome.storage.onChanged` listener in popup, the list will not be updated if the sync storage happens to arrive while the popup is open. That means inconsistent state in the UI.

2. This is a bad way to test if something is an actual item:

       if((typeof key === "string") && (key !== "count"))

  It essentially makes it impossible to have other configuration keys (like #12) without changing this.

  You already have a much more sane way in `isValidSyncItem` - so use a similar approach when you need to get a list of items. Perhaps even better to have a function that returns an Array of all valid items.

3. Speaking of that, your current code in `init` in popup completely bypasses core and does its own thing with the storage. This has to be avoided, for example with a function described above.

**Comment by napsternxg** [comment]
@kav2k great suggestions. I have incorporated these changes and will update the branch. Do try it out.

**Comment by kav2k** [comment]
See my comment; the code is (presumably) working now, so this can be merged. There are still things that can be improved, but the goal is reached, I think.

**Comment by napsternxg** [comment]
Yes, I think I will merge it today. Would you like to give testing it a try. Also do check #13 , I have added support for that as well. Overall, I think this should be ready to release.

**Comment by kav2k** [comment]
I say - merge this in, I'll do a testing run. If able, that is - I'll be quite busy until the end of next week. Which means #12 might be late for this release.
