### ISSUE TITLE
Cannot export to JSON & iPhone support

### ISSUE THREAD

**Issue by MarkosVakondios** [napsternxg/ReadLater#31]
Any work around for phone versions of Chrome which do not support extensions?

Tried at least to export as JSON and then convert and upload to cloud for access from my phone, but the export to JSON function is not working in Chrome desktop windows Version 65.0.3325.181 (Official Build) (64-bit)

Popup page console messages:
![image](https://user-images.githubusercontent.com/2356729/38994359-d9c23760-43ee-11e8-8426-df2896223b8d.png)

**Comment by napsternxg** [comment]
Please check your pop-up blocker. It might be not allowing any downloads. 

Also, in your console you can type the following command to see the JSON of the saved links. 

```javascript

readLaterObject.getValidSyncItems(function(syncItems){
console.log("Downloading items");
console.log(JSON.stringify(syncItems, 0, 2));
});
```
