### ISSUE TITLE
Is there a way to remove the badge icon telling you the number of links? 

### ISSUE THREAD

**Issue by Ivan-Dimitrov** [napsternxg/ReadLater#32]
Before reporting your issue please take time to report the following:

* [x] ReadLater version you are using
  - Right click on ReadLater icon in your browser
  - Select manage extensions.
  - Version number is listed right next to the ReadLater app name. 
* [x] Messages from the console of your popup page. 
  - Right click on ReadLater icon in your browser
  - Select inspect popup.
  - Go to the console tab
  - Copy any messages printed there.
* [x] Messages from the console of your backgroud page. 
  - Right click on ReadLater icon in your browser
  - Select manage extensions.
  - Click the backgroud page of your ReadLater app.
  - Go to the console tab
  - Copy any messages printed there.

**Comment by napsternxg** [comment]
Why is this feature needed? Currently there is no way to disable this badge. 

Not enough information. Closing.

**Comment by Ivan-Dimitrov** [comment]
Not everyone wants badge icon up there or the number of items saved to be displayed. I want to be able to save items without a notification at the top of my browser reminding me.
