### ISSUE TITLE
Explation for PR #34 

### ISSUE THREAD

**Issue by LasyIsLazy** [napsternxg/ReadLater#35]
I made some updates in PR #34:
## 1. Fix non-English characters' ellipsis.
Before:
![readlater-bug](https://user-images.githubusercontent.com/18400251/57897763-f9012d00-7888-11e9-961a-4e3ee0c9ff5d.png)
Now:
![readlater-bug-fixed](https://user-images.githubusercontent.com/18400251/57897838-31087000-7889-11e9-8ce8-c5e2415f35ef.png)
## 2. Remove links' underlines.
It looks messy when there are too many underlines. Now, the underline will shows only mouse over the link.
## 3. Make remove button character center.
The 'x' character is not vertial center.
Before:
![btn-before](https://user-images.githubusercontent.com/18400251/57898197-9a3cb300-788a-11e9-8105-c8cef73f7671.png)
After:
![btn-after](https://user-images.githubusercontent.com/18400251/57898204-9d37a380-788a-11e9-9e50-f85a33d3d50d.png)

**Comment by napsternxg** [comment]
This is great. It closes #34

**Comment by napsternxg** [comment]
Closed via #34
