### ISSUE TITLE
How to restore or export URL?

### ISSUE THREAD

**Issue by wildafrica** [napsternxg/ReadLater#9]
Hello,

I would like to ask you. How to locate saved URL or how to export saved URL? I reinstall my PC and saved URL disappeared. I have URL on other PC in other Chrome broswer but how can I export them? 

Or where can I locate saved URL? I have backup USER folder from windows 10.

Thank you.

**Comment by angeliski** [comment]
Hi @wildafrica . You tried make login in your new chrome installation? I think that extension use Chrome Sync for the URL backups. :)

**Comment by napsternxg** [comment]
@angeliski is right. I use Chrome Sync for managing URL data across chrome installations.
